# Generated by Django 4.0.5 on 2022-08-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0003_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('comentario', models.TextField(max_length=400)),
            ],
        ),
    ]
