# Generated by Django 4.0.5 on 2022-08-05 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0004_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
