# Generated by Django 4.0.5 on 2022-08-09 20:16

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Articulos', '0005_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='subTitulo',
            field=models.CharField(default='Holas', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrada',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
