# Generated by Django 4.0.5 on 2022-08-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0006_entrada_subtitulo_alter_entrada_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='subTitulo',
            new_name='subtitulo',
        ),
    ]
