# Generated by Django 4.0.5 on 2022-08-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0007_rename_subtitulo_entrada_subtitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('comentario', models.TextField(max_length=400)),
            ],
        ),
    ]
