# Generated by Django 4.0.5 on 2022-08-11 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0008_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='entrada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Articulos.entrada'),
            preserve_default=False,
        ),
    ]
