# Generated by Django 4.0.5 on 2022-08-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0009_comentarios_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='entrada',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='entrada_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
