# Generated by Django 4.0.5 on 2022-08-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('mensaje', models.TextField(max_length=250)),
                ('autor', models.CharField(max_length=50)),
                ('leido', models.BooleanField(default=False)),
            ],
        ),
    ]
