# Generated by Django 4.0.5 on 2022-08-10 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mensajes', '0002_mensajes_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='nombre',
            field=models.CharField(default='salida', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
